In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)

## Import dataset

In [3]:
df= pd.read_csv("C:/Users/Asus/Desktop/data science/fraud detection/Data.csv")

In [4]:
df.head()

,Unnamed: 0,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud
0,0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,Uber,US,US,2.0,1.0,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
1,1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,AMC #191138,US,US,9.0,1.0,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,True,NaN,NaN,False,False
2,2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
3,3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
4,4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,2.0,1.0,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,NaN,0.0,NaN,NaN,NaN,True,NaN,NaN,False,False

In [5]:
df.shape

(786363, 30)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786363 entries, 0 to 786362
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                786363 non-null  int64
 1   accountNumber             786363 non-null  int64
 2   customerId                786363 non-null  int64
 3   creditLimit               786363 non-null  int64
 4   availableMoney            786363 non-null  float64
 5   transactionDateTime       786363 non-null  object
 6   transactionAmount         786363 non-null  float64
 7   merchantName              786363 non-null  object
 8   acqCountry                781801 non-null  object
 9   merchantCountryCode       785639 non-null  object
 10  posEntryMode              782309 non-null  float64
 11  posConditionCode          785954 non-null  float64
 12  merchantCategoryCode      786363 non-null  object
 13  currentExpDate            786363 non-null  object
 14  accountOpenDate           786363 non-null  object
 15  dateOfLastAddressChange   786363 non-null  object
 16  cardCVV                   786363 non-null  int64
 17  enteredCVV                786363 non-null  int64
 18  cardLast4Digits           786363 non-null  int64
 19  transactionType           785665 non-null  object
 20  echoBuffer                0 non-null       float64
 21  currentBalance            786363 non-null  float64
 22  merchantCity              0 non-null       float64
 23  merchantState             0 non-null       float64
 24  merchantZip               0 non-null       float64
 25  cardPresent               786363 non-null  bool
 26  posOnPremises             0 non-null       float64
 27  recurringAuthInd          0 non-null       float64
 28  expirationDateKeyInMatch  786363 non-null  bool
 29  isFraud                   786363 non-null  bool
dtypes: bool(3), float64(11), int64(7), object(9)
memory usage: 164.2+ MB

## data pre-processing

In [7]:
df.isnull().sum()

Unnamed: 0                       0
accountNumber                    0
customerId                       0
creditLimit                      0
availableMoney                   0
transactionDateTime              0
transactionAmount                0
merchantName                     0
acqCountry                    4562
merchantCountryCode            724
posEntryMode                  4054
posConditionCode               409
merchantCategoryCode             0
currentExpDate                   0
accountOpenDate                  0
dateOfLastAddressChange          0
cardCVV                          0
enteredCVV                       0
cardLast4Digits                  0
transactionType                698
echoBuffer                  786363
currentBalance                   0
merchantCity                786363
merchantState               786363
merchantZip                 786363
cardPresent                      0
posOnPremises               786363
recurringAuthInd            786363
expirationDateKeyInMatch         0
isFraud                          0
dtype: int64

## Dropping features which contains large number of null values

In [8]:
df.drop(['echoBuffer',"merchantName", 'merchantCity', 'merchantState','merchantZip', 'posOnPremises','recurringAuthInd'],axis=1, inplace=True)

In [9]:
df.head()

,Unnamed: 0,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud
0,0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,US,US,2.0,1.0,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,0.0,False,False,False
1,1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,US,US,9.0,1.0,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,True,False,False
2,2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
3,3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
4,4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,US,US,2.0,1.0,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False

In [10]:
df.isnull().sum()

Unnamed: 0                     0
accountNumber                  0
customerId                     0
creditLimit                    0
availableMoney                 0
transactionDateTime            0
transactionAmount              0
acqCountry                  4562
merchantCountryCode          724
posEntryMode                4054
posConditionCode             409
merchantCategoryCode           0
currentExpDate                 0
accountOpenDate                0
dateOfLastAddressChange        0
cardCVV                        0
enteredCVV                     0
cardLast4Digits                0
transactionType              698
currentBalance                 0
cardPresent                    0
expirationDateKeyInMatch       0
isFraud                        0
dtype: int64

## Handling missing values

In [11]:
df['posConditionCode']= df['posConditionCode'].fillna(df['posConditionCode'].mean()) 
df['posEntryMode']= df['posEntryMode'].fillna(df['posEntryMode'].mean())

In [12]:
df.dropna(inplace = True)

In [13]:
df.isnull().sum()

Unnamed: 0                  0
accountNumber               0
customerId                  0
creditLimit                 0
availableMoney              0
transactionDateTime         0
transactionAmount           0
acqCountry                  0
merchantCountryCode         0
posEntryMode                0
posConditionCode            0
merchantCategoryCode        0
currentExpDate              0
accountOpenDate             0
dateOfLastAddressChange     0
cardCVV                     0
enteredCVV                  0
cardLast4Digits             0
transactionType             0
currentBalance              0
cardPresent                 0
expirationDateKeyInMatch    0
isFraud                     0
dtype: int64

In [14]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [15]:
df.head(10)

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud
0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,US,US,2.0,1.0,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,0.0,False,False,False
1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,US,US,9.0,1.0,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,True,False,False
2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,US,US,2.0,1.0,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False
5,830329091,830329091,5000,5000.0,2016-04-19T16:24:27,30.76,US,US,2.0,1.0,fastfood,01/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False
6,830329091,830329091,5000,5000.0,2016-05-21T14:50:35,57.28,US,US,2.0,1.0,fastfood,05/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False
7,830329091,830329091,5000,5000.0,2016-06-03T00:31:21,9.37,US,US,5.0,1.0,fastfood,01/2021,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False
9,830329091,830329091,5000,5000.0,2016-07-11T10:47:16,164.37,US,US,5.0,8.0,fastfood,04/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False
10,830329091,830329091,5000,5000.0,2016-09-07T20:22:47,160.18,US,US,2.0,8.0,fastfood,05/2023,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False

## Exploratory data analysis

In [16]:
df['transactionDateTime'] = pd.to_datetime(df['transactionDateTime'])
df['dateOfLastAddressChange'] = pd.to_datetime(df['dateOfLastAddressChange'])
df['accountOpenDate'] = pd.to_datetime(df['accountOpenDate'])
df['currentExpDate'] = pd.to_datetime(df['currentExpDate'])

In [17]:
df["transaction_day"]= pd.to_datetime(df.transactionDateTime,format="%Y/%m/%d").dt.day
df["transaction_month"]= pd.to_datetime(df.transactionDateTime,format="%Y/%m/%d").dt.month
df["transaction_year"]= pd.to_datetime(df.transactionDateTime,format="%Y/%m/%d").dt.year
df["transaction_hour"]= pd.to_datetime(df.transactionDateTime,format="%Y/%m/%d").dt.hour
df["transaction_minute"]= pd.to_datetime(df.transactionDateTime,format="%Y/%m/%d").dt.minute

In [18]:
df.drop(["transactionDateTime"],axis=1,inplace=True)

In [19]:
df["expiry year"]= pd.to_datetime(df.currentExpDate,format="%Y/%m/%d").dt.year
df["expiry month"]= pd.to_datetime(df.currentExpDate,format="%Y/%m/%d").dt.month

In [20]:

df.drop(["currentExpDate"],axis=1,inplace=True)

In [21]:
df["accountopen year"]= pd.to_datetime(df.accountOpenDate,format="%Y/%m/%d").dt.year
df["accountopen month"]= pd.to_datetime(df.accountOpenDate,format="%Y/%m/%d").dt.month
df["accountopen day"]= pd.to_datetime(df.accountOpenDate,format="%Y/%m/%d").dt.day

In [22]:
df.drop(["accountOpenDate"],axis=1,inplace=True)

In [23]:

df["last_address_change year"]= pd.to_datetime(df.dateOfLastAddressChange,format="%Y/%m/%d").dt.year
df["last_address_change month"]= pd.to_datetime(df.dateOfLastAddressChange,format="%Y/%m/%d").dt.month
df["last_address_change day"]= pd.to_datetime(df.dateOfLastAddressChange,format="%Y/%m/%d").dt.day

In [24]:
df.drop(["dateOfLastAddressChange"],axis=1,inplace=True)

In [25]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionAmount,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,cardCVV,enteredCVV,cardLast4Digits,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,transaction_day,transaction_month,transaction_year,transaction_hour,transaction_minute,expiry year,expiry month,accountopen year,accountopen month,accountopen day,last_address_change year,last_address_change month,last_address_change day
0,737265056,737265056,5000,5000.0,98.55,US,US,2.0,1.0,rideshare,414,414,1803,PURCHASE,0.0,False,False,False,13,8,2016,14,27,2023,6,2015,3,14,2015,3,14
1,737265056,737265056,5000,5000.0,74.51,US,US,9.0,1.0,entertainment,486,486,767,PURCHASE,0.0,True,False,False,11,10,2016,5,5,2024,2,2015,3,14,2015,3,14
2,737265056,737265056,5000,5000.0,7.47,US,US,9.0,1.0,mobileapps,486,486,767,PURCHASE,0.0,False,False,False,8,11,2016,9,18,2025,8,2015,3,14,2015,3,14
3,737265056,737265056,5000,5000.0,7.47,US,US,9.0,1.0,mobileapps,486,486,767,PURCHASE,0.0,False,False,False,10,12,2016,2,14,2025,8,2015,3,14,2015,3,14
4,830329091,830329091,5000,5000.0,71.18,US,US,2.0,1.0,fastfood,885,885,3143,PURCHASE,0.0,True,False,False,24,3,2016,21,4,2029,10,2015,8,6,2015,8,6

## Handling categorical data

In [26]:
df=pd.get_dummies(df,drop_first=True)

In [27]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionAmount,posEntryMode,posConditionCode,cardCVV,enteredCVV,cardLast4Digits,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,transaction_day,transaction_month,transaction_year,transaction_hour,transaction_minute,expiry year,expiry month,accountopen year,accountopen month,accountopen day,last_address_change year,last_address_change month,last_address_change day,acqCountry_MEX,acqCountry_PR,acqCountry_US,merchantCountryCode_MEX,merchantCountryCode_PR,merchantCountryCode_US,merchantCategoryCode_auto,merchantCategoryCode_cable/phone,merchantCategoryCode_entertainment,merchantCategoryCode_fastfood,merchantCategoryCode_food,merchantCategoryCode_food_delivery,merchantCategoryCode_fuel,merchantCategoryCode_furniture,merchantCategoryCode_gym,merchantCategoryCode_health,merchantCategoryCode_hotels,merchantCategoryCode_mobileapps,merchantCategoryCode_online_gifts,merchantCategoryCode_online_retail,merchantCategoryCode_online_subscriptions,merchantCategoryCode_personal care,merchantCategoryCode_rideshare,merchantCategoryCode_subscriptions,transactionType_PURCHASE,transactionType_REVERSAL
0,737265056,737265056,5000,5000.0,98.55,2.0,1.0,414,414,1803,0.0,False,False,False,13,8,2016,14,27,2023,6,2015,3,14,2015,3,14,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
1,737265056,737265056,5000,5000.0,74.51,9.0,1.0,486,486,767,0.0,True,False,False,11,10,2016,5,5,2024,2,2015,3,14,2015,3,14,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,737265056,737265056,5000,5000.0,7.47,9.0,1.0,486,486,767,0.0,False,False,False,8,11,2016,9,18,2025,8,2015,3,14,2015,3,14,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
3,737265056,737265056,5000,5000.0,7.47,9.0,1.0,486,486,767,0.0,False,False,False,10,12,2016,2,14,2025,8,2015,3,14,2015,3,14,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
4,830329091,830329091,5000,5000.0,71.18,2.0,1.0,885,885,3143,0.0,True,False,False,24,3,2016,21,4,2029,10,2015,8,6,2015,8,6,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

## Train and Test split

In [28]:
df.columns

Index(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionAmount', 'posEntryMode', 'posConditionCode', 'cardCVV',
       'enteredCVV', 'cardLast4Digits', 'currentBalance', 'cardPresent',
       'expirationDateKeyInMatch', 'isFraud', 'transaction_day',
       'transaction_month', 'transaction_year', 'transaction_hour',
       'transaction_minute', 'expiry year', 'expiry month', 'accountopen year',
       'accountopen month', 'accountopen day', 'last_address_change year',
       'last_address_change month', 'last_address_change day',
       'acqCountry_MEX', 'acqCountry_PR', 'acqCountry_US',
       'merchantCountryCode_MEX', 'merchantCountryCode_PR',
       'merchantCountryCode_US', 'merchantCategoryCode_auto',
       'merchantCategoryCode_cable/phone',
       'merchantCategoryCode_entertainment', 'merchantCategoryCode_fastfood',
       'merchantCategoryCode_food', 'merchantCategoryCode_food_delivery',
       'merchantCategoryCode_fuel', 'merchantCategoryCode_furniture',
       'merchantCategoryCode_gym', 'merchantCategoryCode_health',
       'merchantCategoryCode_hotels', 'merchantCategoryCode_mobileapps',
       'merchantCategoryCode_online_gifts',
       'merchantCategoryCode_online_retail',
       'merchantCategoryCode_online_subscriptions',
       'merchantCategoryCode_personal care', 'merchantCategoryCode_rideshare',
       'merchantCategoryCode_subscriptions', 'transactionType_PURCHASE',
       'transactionType_REVERSAL'],
      dtype='object')

In [30]:
X= df [['accountNumber', 'customerId', 'creditLimit',
       'availableMoney', 'transactionAmount', 'posEntryMode',
       'posConditionCode', 'cardCVV', 'enteredCVV', 'cardLast4Digits',
       'currentBalance', 'cardPresent', 'expirationDateKeyInMatch', 
       'acqCountry_MEX', 'acqCountry_PR', 'acqCountry_US',
       'merchantCountryCode_MEX', 'merchantCountryCode_PR',
       'merchantCountryCode_US', 'merchantCategoryCode_auto',
       'merchantCategoryCode_cable/phone',
       'merchantCategoryCode_entertainment', 'merchantCategoryCode_fastfood',
       'merchantCategoryCode_food', 'merchantCategoryCode_food_delivery',
       'merchantCategoryCode_fuel', 'merchantCategoryCode_furniture',
       'merchantCategoryCode_gym', 'merchantCategoryCode_health',
       'merchantCategoryCode_hotels', 'merchantCategoryCode_mobileapps',
       'merchantCategoryCode_online_gifts',
       'merchantCategoryCode_online_retail',
       'merchantCategoryCode_online_subscriptions',
       'merchantCategoryCode_personal care', 'merchantCategoryCode_rideshare',
       'merchantCategoryCode_subscriptions', 'transactionType_PURCHASE',
       'transactionType_REVERSAL', 'transaction_day', 'transaction_month',
       'transaction_year', 'transaction_hour', 'transaction_minute',
       'expiry year', 'expiry month', 'accountopen year', 'accountopen month',
       'accountopen day', 'last_address_change year',
       'last_address_change month', 'last_address_change day']]
y=df['isFraud']

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

### MODEL TRAINING ON Logistic regression

In [32]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()

In [33]:
model.fit(X_train, y_train)

LogisticRegression()

In [34]:
from sklearn.metrics import accuracy_score

X_train_predict= model.predict(X_train)
training_data_accuracy =accuracy_score(X_train_predict, y_train)

In [35]:
print("accuracy score on training data is : ", training_data_accuracy)

accuracy score on training data is :  0.9843090626565293

In [36]:
X_test_predict= model.predict(X_test)
test_data_accuracy =accuracy_score(X_test_predict, y_test)

In [37]:
print("accuracy score on test data is : ", test_data_accuracy)

accuracy score on test data is :  0.9843234904398256

if we are checking the accuracy in LDA, KNN, CART, NB, SVM model then it is giving same accuracy 98 % . 
So , we can use any model .

## MODEL TRAINING ON RANDOM FOREST CLASSIFIER

In [38]:

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)
rf_conf_matrix = confusion_matrix(y_test, rf_predict)
rf_acc_score = accuracy_score(y_test, rf_predict)
print("confussion matrix")
print(rf_conf_matrix)
print("-------------------------------------------")
print("Accuracy of Random Forest Classifier:",rf_acc_score*100,'\n')
print("-------------------------------------------")
print(classification_report(y_test,rf_predict))

confussion matrix
[[153765      7]
 [  2421     28]]
-------------------------------------------
Accuracy of Random Forest Classifier: 98.44579153890962

-------------------------------------------
              precision    recall  f1-score   support

       False       0.98      1.00      0.99    153772
        True       0.80      0.01      0.02      2449

    accuracy                           0.98    156221
   macro avg       0.89      0.51      0.51    156221
weighted avg       0.98      0.98      0.98    156221

In [41]:
dframe=pd.DataFrame({'actual':y_test,'Predicted':rf_predict})
dframe.head(50)

        actual  Predicted
391854   False      False
316083   False      False
475284   False      False
571455   False      False
334478   False      False
170111   False      False
307688   False      False
436647   False      False
755363   False      False
284769   False      False
721655   False      False
303934   False      False
158881   False      False
600190   False      False
657773   False      False
595638   False      False
196140   False      False
139357   False      False
285570   False      False
525526   False      False
740166   False      False
446467   False      False
575223   False      False
695373   False      False
236155   False      False
317568   False      False
469182   False      False
126098   False      False
116848   False      False
516098   False      False
112162   False      False
546000   False      False
543922   False      False
602780   False      False
754757   False      False
575353   False      False
733367   False      False
616402    True      False
670077   False      False
160858   False      False
457611   False      False
79212    False      False
634234   False      False
663605   False      False
571244   False      False
300966   False      False
6664     False      False
433074   False      False
744628   False      False
169255   False      False